#!/bin/bash
#chkconfig: 2345 10 90
#description:timeCalibration
BASE_DIR="/home/kenneth/" 
JAR_FILE="TimeCalibration-1.0.0.jar"
SERVICE_NAME="timeCalibration"

start()
{
echo "starting ${SERVICE_NAME}..."
cd $BASE_DIR
nohup java -jar $JAR_FILE >/dev/null &
echo "${SERVICE_NAME} started"
}

stop()
{
echo "stopping ${SERVICE_NAME}..."
pid=`ps -ef|grep $JAR_FILE |grep -v grep |awk '{print $2}'`
kill -9 $pid
echo "${SERVICE_NAME} stopped"
}

#重启
restart(){
stop
start
}

case "$1" in
"start")
start
;;

"stop")
stop
;;

"restart")
stop
start
;;

*)
echo "Usage: `basename $0` start|stop|restart"
esac
exit 0

